extends "res://tests/acceptance.gd"

func blocker(at: Vector2, dimensions: Vector2) -> StaticBody2D:
	var body := StaticBody2D.new()
	body.position = at
	var shape := CollisionShape2D.new()
	var rectangle := RectangleShape2D.new()
	rectangle.size = dimensions
	shape.shape = rectangle
	body.add_child(shape)
	game.add_child(body)
	return body

func start() -> void:
	game = load("res://scenes/game.tscn").instantiate() as Node2D
	get_tree().root.add_child(game)
	get_tree().current_scene = game
	refresh_refs()
	await frames(10)
	stage_target(Vector2(850, 900))
	player.position = Vector2(778, 900)
	player.weapons.equip(load("res://data/weapons/bat.tres"))
	var wall := blocker(Vector2(812, 900), Vector2(12, 90))
	await seconds(0.2)
	await tap(&"attack")
	verify(target.health == 3, "Bat cannot hit through thin cover")
	wall.queue_free()
	await frames(3)
	await seconds(0.4)
	await tap(&"attack")
	verify(target.downed, "Bat reaches target after obstruction removed")
	stage_target(Vector2(850, 350))
	var second := PracticeTarget.new()
	second.position = Vector2(855, 375)
	game.add_child(second)
	var behind := PracticeTarget.new()
	behind.position = Vector2(770, 350)
	game.add_child(behind)
	await seconds(0.4)
	await tap(&"attack")
	verify(target.downed and second.downed, "Bat wide arc hits multiple front targets")
	verify(not behind.downed and behind.health == 3, "Bat does not hit behind the player")
	await reset_game()
	car.position = Vector2(600, 450)
	player.position = Vector2(600, 498)
	verify(car.enter(player), "Blocked-exit fixture enters car")
	var obstacles: Array[StaticBody2D] = []
	for point: Vector2 in [Vector2(596, 498), Vector2(596, 402), Vector2(534, 450), Vector2(666, 450)]:
		obstacles.append(blocker(point, Vector2(25, 25)))
	await frames(3)
	verify(not car.try_exit(), "All obstructed exits are refused")
	verify(player.vehicle == car and car.driver == player and not player.visible, "Failed exit preserves driving state")
	obstacles[1].queue_free()
	await frames(3)
	verify(car.try_exit() and player.position.y < 430, "Exit recovers when one door clears")
	await reset_game()
	player.take_hit(3, Vector2.RIGHT * 200)
	verify(player.wounded and player.alive, "First hit wounds")
	player.take_hit(3, Vector2.RIGHT * 200)
	verify(player.alive, "Same-frame second hit is rejected by grace period")
	await seconds(1.2)
	player.take_hit(3, Vector2.RIGHT * 200)
	verify(not player.alive, "Hit after grace period kills")
	await reset_game()
	await key(&"debug_overlay")
	verify(game.run.debug_visible, "Debug action toggles overlay")
	await key(&"toggle_shake")
	verify(not game.feedback.shake_enabled, "Shake action disables camera shake")
	await key(&"pause")
	await key(&"restart")
	refresh_refs()
	verify(player.alive and not get_tree().paused, "Restart works directly from pause")
	print("EDGE CASES COMPLETE: %d checks passed" % checks)
	get_tree().quit(0)
