extends "res://tests/edge_cases.gd"

func latest_pickup() -> WeaponPickup:
	return get_tree().get_nodes_in_group("pickups").back() as WeaponPickup

func start() -> void:
	game = load("res://scenes/game.tscn").instantiate() as Node2D
	get_tree().root.add_child(game)
	get_tree().current_scene = game
	refresh_refs()
	await frames(10)
	stage_target(Vector2(950, 350))
	player.position = Vector2(800, 350)
	player.weapons.equip(load("res://data/weapons/pistol.tres"), 0)
	var pickup_count := get_tree().get_nodes_in_group("pickups").size()
	await tap(&"throw_weapon")
	verify(player.weapons.data.id == &"fists", "Throw immediately restores fists")
	verify(get_tree().get_nodes_in_group("thrown_weapons").size() == 1, "Empty pistol becomes one physical thrown weapon")
	await seconds(0.32)
	verify(target.health == 1 and target.stun > 0, "Empty pistol throw damages and stuns target")
	verify(get_tree().get_nodes_in_group("thrown_weapons").is_empty(), "Impact ends flight")
	verify(get_tree().get_nodes_in_group("pickups").size() == pickup_count + 1, "Impact creates exactly one recoverable weapon")
	var pickup := latest_pickup()
	verify(pickup.ammo == 0 and pickup.data.id == &"pistol", "Thrown pistol preserves empty ammunition")
	player.position = pickup.position
	await tap(&"interact")
	verify(player.weapons.data.id == &"pistol" and player.weapons.ammo == 0, "E recovers empty thrown pistol without ammo exploit")
	await reset_game()
	stage_target(Vector2(950, 350))
	player.position = Vector2(800, 350)
	player.weapons.equip(load("res://data/weapons/bat.tres"))
	await tap(&"throw_weapon")
	await seconds(0.35)
	verify(target.downed, "Thrown bat incapacitates target")
	verify(latest_pickup().data.id == &"bat", "Thrown bat remains recoverable")
	await reset_game()
	stage_target(Vector2(850, 900))
	player.position = Vector2(778, 900)
	player.weapons.equip(load("res://data/weapons/pistol.tres"), 5)
	blocker(Vector2(812, 900), Vector2(8, 90))
	await frames(3)
	await tap(&"throw_weapon")
	await seconds(0.2)
	verify(target.health == 3, "Thrown weapon cannot tunnel through thin cover")
	verify(latest_pickup().position.x < 808 and latest_pickup().ammo == 5, "Wall collision lands weapon on near side with ammo preserved")
	await reset_game()
	player.position = Vector2(200, 850)
	aim(Vector2.DOWN)
	player.weapons.equip(load("res://data/weapons/pistol.tres"), 4)
	await tap(&"throw_weapon")
	await seconds(1.1)
	verify(get_tree().get_nodes_in_group("thrown_weapons").is_empty() and latest_pickup().ammo == 4, "Missed throw settles without losing weapon")
	pickup_count = get_tree().get_nodes_in_group("pickups").size()
	await tap(&"throw_weapon")
	verify(get_tree().get_nodes_in_group("pickups").size() == pickup_count and get_tree().get_nodes_in_group("thrown_weapons").is_empty(), "Fists cannot create a thrown weapon")
	player.position = car.nearest_door(player.position)
	player.weapons.equip(load("res://data/weapons/bat.tres"))
	await tap(&"interact")
	await tap(&"throw_weapon")
	verify(player.weapons.data.id == &"bat" and get_tree().get_nodes_in_group("thrown_weapons").is_empty(), "Throw input is ignored while driving")
	await reset_game()
	stage_target(Vector2(600, 450))
	player.position = Vector2(200, 450) # Keep the observer out of the swept car path.
	car.position = Vector2(500, 450)
	await frames(3)
	car.speed = 500
	car.velocity = Vector2(500, 0)
	car.move_with_impacts(Vector2(140, 0))
	verify(target.downed and target.air_time > 0 and target.velocity.length() > 1000, "Car launches target at high velocity into airborne tumble")
	verify(car.speed > 400 and car.position.x > 590, "Car retains forward momentum and completes motion through target")
	verify(car.health >= 94, "Body impact causes only minor vehicle damage")
	await seconds(0.25)
	verify(target.position.x > 750 and target.visual_lift() > 20, "Launched dummy visibly flies away from impact")
	await reset_game()
	stage_target(Vector2(570, 450))
	player.position = Vector2(200, 450) # Keep the observer out of the swept car path.
	car.position = Vector2(500, 450)
	blocker(Vector2(660, 450), Vector2(10, 100))
	await frames(3)
	car.speed = 500
	car.velocity = Vector2(500, 0)
	car.move_with_impacts(Vector2(220, 0))
	verify(target.downed and car.position.x < 617 and car.speed <= 0, "Wall behind launched target still blocks and bounces car")
	await reset_game()
	car.position = Vector2(600, 850)
	stage_target(Vector2(700, 850))
	player.position = Vector2(200, 850)
	car.take_hit(100, Vector2.ZERO)
	verify(not car.disabled and car.failure_timer > 2.9, "Lethal damage starts full three-second warning")
	car.take_hit(100, Vector2.ZERO)
	verify(car.failure_timer <= 3.0, "Additional hits cannot reset explosion countdown")
	await seconds(2.0)
	verify(not car.disabled and target.health == 3, "No premature explosion damage during warning")
	await seconds(1.5)
	verify(car.disabled and target.downed, "Explosion deals radial target damage")
	verify(player.alive, "Outside blast radius is safe")
	var downs_before: int = game.run.downs
	car.explode()
	await frames(3)
	verify(game.run.downs == downs_before, "Wreck cannot explode a second time")
	await reset_game()
	car.position = Vector2(600, 850)
	stage_target(Vector2(700, 850))
	player.position = Vector2(760, 850)
	blocker(Vector2(660, 850), Vector2(12, 150))
	await frames(3)
	car.explode()
	verify(target.health == 3 and not player.wounded and player.alive, "Solid cover shields targets and player from blast")
	await reset_game()
	car.position = Vector2(600, 850)
	player.position = Vector2(750, 850)
	car.explode()
	verify(player.wounded and player.alive and player.impulse.length() > 0, "Outer blast wounds and pushes player")
	await reset_game()
	car.position = Vector2(600, 850)
	player.position = Vector2(660, 850)
	car.explode()
	verify(not player.alive and game.run.ended, "Point-blank blast kills player and ends run")
	await reset_game()
	car.position = Vector2(600, 850)
	player.position = Vector2(600, 898)
	verify(car.enter(player), "Explosion occupant fixture enters car")
	car.take_hit(100, Vector2.ZERO)
	await seconds(3.5)
	verify(not player.alive and player.vehicle == null and car.driver == null, "Remaining inside exploding car kills occupant and clears references")
	await reset_game()
	car.position = Vector2(600, 850)
	player.position = Vector2(600, 898)
	car.enter(player)
	car.take_hit(100, Vector2.ZERO)
	verify(car.try_exit(), "Exit remains available during explosion countdown")
	Input.action_press("move_down")
	await seconds(1.0)
	Input.action_release("move_down")
	await seconds(2.5)
	verify(car.disabled and player.alive and not player.wounded, "Exiting and running beyond radius survives explosion")
	await reset_game()
	verify(player.alive and car.health == 100 and get_tree().get_nodes_in_group("explosions").is_empty() and get_tree().get_nodes_in_group("thrown_weapons").is_empty(), "Restart clears blasts, thrown weapons and wreck state")
	print("PHYSICS REVISION COMPLETE: %d checks passed" % checks)
	get_tree().quit(0)

# Physics assertions wait for simulated time, not wall time under parallel CPU load.
func seconds(duration: float) -> void:
	var elapsed: float = 0
	while elapsed < duration:
		await get_tree().physics_frame
		elapsed += get_physics_process_delta_time()
